name: Central Basic CI

on:
  workflow_call:
    # 1. WE DECLARE THE INPUTS HERE
    inputs:
      app_name:
        description: "The name of the application being built"
        required: true
        type: string

    
    # 2. Declare secrets contract here       
    secrets:
      MY_DB_PASSWORD:
        description: "The database password from the app repo"
        required: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: say hellow 
        run: echo "hellow from Central repo !! -- resuable workflow executed succesfully"
     
      # 2. WE USE THE INPUT HERE
      - name: Print the Passed Variable
        run: echo "The Caller repo told me to build the application named -> ${{ inputs.app_name }}"
      #  run: echo " descprtion line - ${{ inputs.app_name.description }}"
    
      # 3. PROVE THE SECRET ARRIVED SAFELY
      - name: Verify Secret Transfer
        run: |
          echo "Testing if the secret successfully crossed the repository bridge..."
          echo "The database password is: ${{ secrets.MY_DB_PASSWORD }}"
      
  
mp over to voya-app-repo/.github/workflows/trigger.yaml. Update it t
